///// General
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const SET_BASKET_LIST = 'SET_BASKET_LIST';
export const ADD2_BASKET_LIST = 'ADD_BASKET_LIST';
export const REMOVE_FROM_BASKET_LIST = 'REMOVE_BASKET_LIST';
